// copiar respúesta en el portapapeles
// crl + shift + p y escribir: paste JSON as Code
// le damos el nombre

// Generated by https://quicktype.io
export interface PokemonsResponse {
  count: number;
  next: string;
  previous: null;
  results: Result[];
}

export interface Result {
  name: string;
  url: string;
}
